### ISSUE TITLE
Join lines that share specified properties

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/tilelive-decorator#2]
Features with the same properties within a tile should be joined to avoid the overhead of having distinct geometries. Ideally this is exposed as an option that is passed to the decorator.

For example: `{ linejoin: true, linejoinUniqueBy: [ 'speedClass', 'FRC' ] }`

@mourner - Can you grab this?

cc @yhahn

**Comment by mourner** [comment]
Grabbing.

**Comment by mourner** [comment]
-> #4
