### ISSUE TITLE
All numbers are encoded as floats

### ISSUE THREAD

**Issue by mourner** [mapbox/tilelive-decorator#3]
All number values are [encoded as floats](https://github.com/mapbox/tilelive-decorator/blob/master/index.js#L195). This has two consequences:
- integers are not efficiently packed using varint, leading to bulkier size
- bigger integers loose precision when packed as 32-bit floats

Instead integers should be encoded as either `uint` or `sint` depending on sign.

cc @aaronlidman

**Comment by kkaefer** [comment]
nice find

**Comment by mourner** [comment]
-> #4
